### ISSUE TITLE
Unable to upload anything that takes longer 60 seconds, also attempting upload to the wrong servers?

### ISSUE THREAD

**Issue by dimetime** [RealDolos/node-volaupload#3]
I was [recommended](https://github.com/szero/volascripts.sh/issues/8) to give a try to this variation of volaupload. However, it seems to be also the 60 second rule seems to apply to this one as well. Also it looks like this one is also attempting to upload to nonupload-servers such as dl1, or dl10 gets reported as dl1?

`$ volaupload -r 1bqg3h5ww -u Volaphile ./600 
Make a .vola.conf already, pls
Deploying one botnet payload to 1 rooms
Connecting to mainframe cluster https://volafile.org/r/1bqg3h5ww
600 [################################################################################################################################################################################################################################] 100.0% 600.0M/600.0M dl7  9.97M/s  60.2s
Failed to upload /tmp/600: Upload failed! <html> 
  <head>
    <title>502 - Volafile will be right back</title>
  </head> 
  <body style="font-family:Arial,Helvetica,sans-serif;">
    <div style="margin: 0 auto; width: 960px;"> 
		<h2>502 - Volafile will be right back</h2>
        <p>
		Volafile is currently experiencing issues, but will be back soon.
        </p>
        <p>
        Refresh this page to retry.	
        </p>
    </div>
	<script type="text/javascript">
		setTimeout(function() { location.reload() }, 30000 + Math.floor(Math.random() * 3000));
	</script>
  </body> 
</html>
 (Attempt 1)
100 [################################################################################################################################################################################################################################] 100.0% 600.0M/600.0M dl1  9.97M/s  60.2s
Failed to upload /tmp/600: Upload failed! <html> 
  <head>
    <title>502 - Volafile will be right back</title>
  </head> 
  <body style="font-family:Arial,Helvetica,sans-serif;">
    <div style="margin: 0 auto; width: 960px;"> 
		<h2>502 - Volafile will be right back</h2>
        <p>
		Volafile is currently experiencing issues, but will be back soon.
        </p>
        <p>
        Refresh this page to retry.	
        </p>
    </div>
	<script type="text/javascript">
		setTimeout(function() { location.reload() }, 30000 + Math.floor(Math.random() * 3000));
	</script>
  </body> 
</html>
 (Attempt 2)
600 [################################################################################################################################################################################################################################] 100.0% 600.0M/600.0M dl1  9.97M/s  60.2s
Failed to upload /tmp/600: request to https://dl10.volafile.org/upload?room=1bqg3h5ww&key=Ddi_ef9symH49&filename=600 failed, reason: socket hang up (Attempt 3)

`

**Comment by RealDolos** [comment]
Yeah, lain messed up the servers so connection are cut after 60s. The lastest volaupload release implements upload resuming to work around that (and also fixes the incorrect display of server).

I just published it on npm as well. it should be available soon
